### ISSUE TITLE
Features?

### ISSUE THREAD

**Issue by pwFoo** [mgoltzsche/runc-compose#1]
@mgoltzsche 
What features has runc-compose? Any examples or demo?
Last commit is 2 years old. Is it still usable or end of life?

**Comment by mgoltzsche** [comment]
@pwFoo this is just private garbage in a public repo: it was a naive quick initial attempt to fork [rkt-compose](https://github.com/mgoltzsche/rkt-compose) and make it work with runc instead of rkt. In another repo I continued the runc-based approach with [ctnr](https://github.com/mgoltzsche/ctnr) focussing on rootless container execution. Thus ctnr's compose support never became really mature. ctnr is now also deprecated in favour of [podman](https://github.com/containers/libpod) (runc-based rootless daemonless docker-compatible container engine). In theory podman could also work with docker-compose due to its docker CLI compatibility but I haven't tried it yet since I wasn't working with compose that much anymore lately. You can have a look at my docker container image [mgoltzsche/podman](https://github.com/mgoltzsche/podman-static) to quickly play around with podman or install it locally.
